sudo: required
services:
  - docker

scripts:
  - docker build -t matiasmiguez/node .
  - docker images matiasmiguez/node

before_deploy:
  - docker login -u matiasmiguez -p 31552083Matias

deploy:
  provider: script
  script: docker push matiasmiguez/node
  on:
    branch: main
